sudo: required
language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .

script:
  - py.test --cov

after_success:
  - codecov

notifications:
    email: raphaelvallat9@gmail.com
    
